#!/bin/bash

dir1="$1"
shift
dir2="$1"

if [ ! -d "$dir1" ]; then
    echo "$dir1 not found"
    exit 1
fi
if [ ! -d "$dir2" ]; then
    echo "$dir2 not found"
    exit 1
fi

if [ -d trans ]; then
    echo "Overwrite existing dir: $trans? (Enter or Ctrl-C)"
    read a
fi

TOOLS="$(dirname $0)/tools"

###################################################################
echo "Transform files to ignore comments"
mkdir -p trans
rm -rf trans/*
echo "> transform: $dir1"
c=0
find "$dir1" | grep -e '\.c$' -e '\.cpp$' -e '\.h$' | while read line;
do
    echo ">> [$c] $line"
    let c++
    $TOOLS/transformFile.sh $line trans
done
echo "> transform: $dir2"
c=0
find "$dir2" | grep -e '\.c$' -e '\.cpp$' -e '\.h$' | while read line;
do
    echo ">> [$c] $line"
    let c++
    $TOOLS/transformFile.sh $line trans
done

TSN="$(date +%Y-%m-%d_%H%M%S)_$USER"
echo "Diff the tree"
diff -w -B -u -r "$dir1" "$dir2" > trans/diff_$TSN.diff.utf8
iconv --from-code UTF-8 --to-code US-ASCII -c trans/diff_$TSN.diff.utf8 > trans/diff_$TSN.diff
echo "Convert to HTML"
python $TOOLS/diff2html.py -i trans/diff_$TSN.diff -o trans/diff_$TSN.html
echo "done"
